from __future__ import annotations

import csv
from pathlib import Path
from typing import Any
import yaml


def _last_numeric(values: list[str]) -> float | None:
    for value in reversed(values):
        try:
            return float(value)
        except (ValueError, TypeError):
            continue
    return None


def parse_ultralytics_results_csv(csv_path: str) -> dict[str, Any]:
    """Read `results.csv` generated by an Ultralytics training run."""
    path = Path(csv_path)
    if not path.exists():
        return {}
    with open(path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        rows = list(reader)
    if not rows:
        return {}
    header = list(rows[0].keys())
    output: dict[str, Any] = {}
    for key in header:
        values = [row.get(key, "") for row in rows]
        numeric = _last_numeric(values)
        output[key] = numeric if numeric is not None else values[-1]

    # Normalise common names to the labels requested by the dashboard.
    alias = {
        "epoch": "epoch",
        "train/box_loss": "train/box_loss",
        "train/cls_loss": "train/cls_loss",
        "train/obj_loss": "train/obj_loss",
        "val/box_loss": "val/box_loss",
        "val/cls_loss": "val/cls_loss",
        "val/obj_loss": "val/obj_loss",
        "metrics/mAP50(B)": "mAP50",
        "metrics/mAP50-95(B)": "mAP50-95",
        "metrics/precision(B)": "precision",
        "metrics/recall(B)": "recall",
    }
    normalized: dict[str, Any] = {}
    for raw_key, value in output.items():
        normalized[alias.get(raw_key, raw_key)] = value
    return normalized


def try_parse_model_metadata(weight_path: str) -> dict[str, Any]:
    """Return best-effort model metadata without importing torch in the GUI thread."""
    result: dict[str, Any] = {}
    weight = Path(weight_path)
    result["model_path"] = str(weight)
    result["size_bytes"] = weight.stat().st_size if weight.exists() else 0
    # Ultralytics writes metadata alongside trained models, but loading it here
    # is deferred to avoid a potentially expensive torch import.
    return result


def parse_ultralytics_args_yaml(weight_path: str) -> dict[str, Any]:
    """Locate and parse an Ultralytics `args.yaml` near the selected weights."""
    weight = Path(weight_path)
    candidates = [
        weight.parent / "args.yaml",
        weight.parent.parent / "args.yaml",
        weight.parent.parent.parent / "args.yaml",
    ]
    for candidate in candidates:
        if candidate.exists():
            try:
                data = yaml.safe_load(candidate.read_text(encoding="utf-8")) or {}
                return {str(k): v for k, v in data.items()}
            except Exception:
                return {}
    return {}


def flatten_model_metrics(metrics: dict[str, Any]) -> dict[str, Any]:
    """Flatten nested metrics into a single-level display dictionary."""
    flat: dict[str, Any] = {}
    for key, value in metrics.items():
        if isinstance(value, dict):
            for sub_key, sub_value in value.items():
                flat[f"{key}.{sub_key}"] = sub_value
        else:
            flat[key] = value
    return flat
